version: "3"

# GitHub Actions output grouping
output:
  group:
    begin: "::group::{{.TASK}}"
    end: "::endgroup::"

vars:
  CLI_NAME: "postgres-cli"
  GOBIN: '{{.GOBIN | default "$(go env GOPATH)/bin"}}'

tasks:
  build:
    desc: Build the postgres-cli and install to GOBIN

    cmds:
      - echo "Building postgres-cli..."
      - |
        GOBIN_PATH="$(go env GOPATH)/bin"
        echo "Installing to: $GOBIN_PATH/{{.CLI_NAME}}"
        go build -ldflags "-s -w" -o "$GOBIN_PATH/{{.CLI_NAME}}" ./cmd
      - echo "✅ Built and installed {{.CLI_NAME}} to $(go env GOPATH)/bin"
    method: timestamp

  install:
    desc: Install the CLI to GOBIN (alias for build)
    cmds:
      - task: build

  test:
    desc: Run all CLI-related tests
    cmds:
      - echo "Running CLI tests..."
      - go test ./cmd/... ./pkg/... -v -cover
      - echo "✅ CLI tests passed"

  ci:
    desc: Run complete CI pipeline for CLI
    cmds:
      - task: check-dependencies
      - task: build
      - task: test
      - echo "🎉 CLI CI pipeline completed successfully"

  fmt:
    desc: Format CLI code
    cmds:
      - echo "Formatting CLI code..."
      - go fmt ./cmd/... ./pkg/...
      - echo "✅ CLI code formatted"

  lint:
    desc: Lint CLI code
    cmds:
      - echo "Linting CLI code..."
      - go vet ./cmd/... ./pkg/...
      - echo "✅ CLI code linting completed"
